const fs = require('fs');
const axios = require('axios');
const XLSX = require('xlsx');
const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY; 
const EXCEL_SOURCE_URL = "https://raw.githubusercontent.com/" + process.env.GITHUB_REPOSITORY + "/main/Stock_list.xlsx"; 
const FINMIND_TOKEN = process.env.FINMIND_TOKEN;

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {\n  auth: { persistSession: false },\n  realtime: { global: false }\n});

const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

function formatDateToString(dateObj) {\n  const yyyy = dateObj.getFullYear();\n  const mm = String(dateObj.getMonth() + 1).padStart(2, '0');\n  const dd = String(dateObj.getDate()).padStart(2, '0');\n  return `${yyyy}-${mm}-${dd}`;\n}

async function run() {\n  try {\n    console.log("🚀 開始執行【智慧增量 + 技術指標增量計算】同步流程...");

    // 1. 載入標的清單
    const response = await axios.get(EXCEL_SOURCE_URL, { responseType: 'arraybuffer' });\n    const workbook = XLSX.read(response.data, { type: 'buffer' });\n    const stockMap = new Map();\n    workbook.SheetNames.forEach(name => {\n      const sheet = workbook.Sheets[name];\n      const json = XLSX.utils.sheet_to_json(sheet);\n      json.forEach(row => {\n        const sId = String(row['股票代號'] || row['代號'] || '').trim();\n        const sName = String(row['股票名稱'] || row['名稱'] || '').trim();\n        if (!sId) return;\n        if (!stockMap.has(sId)) {\n          stockMap.set(sId, { stock_id: sId, stock_name: sName, sheet_tags: [] });\n        }\n        if (!stockMap.get(sId).sheet_tags.includes(name)) {\n          stockMap.get(sId).sheet_tags.push(name);\n        }\n      });\n    });

    const dbStockData = Array.from(stockMap.values());\n    console.log(`📊 本次欲檢查並同步的雲端股票總數: ${dbStockData.length} 檔`);

    if (dbStockData.length === 0) return;

    // 2. 自動判定起訖日期 (智慧增量)
    const { data: lastRecord, error: dateErr } = await supabase\n      .from('stock_chips_daily')\n      .select('date')\n      .order('date', { ascending: false })\n      .limit(1);\n      \n    if (dateErr) console.log("⚠️ 偵測最大日期異常(可能尚未有任何資料):", dateErr.message);

    let startDate = new Date('2026-01-01');\n    if (lastRecord && lastRecord.length > 0 && lastRecord[0].date) {\n      const lastDate = new Date(lastRecord[0].date);\n      lastDate.setDate(lastDate.getDate() + 1);\n      startDate = lastDate;\n    }\n    \n    const today = new Date();\n    if (startDate > today) {\n      console.log("✨ 雲端資料庫已是最新，無須增量更新。");\n      return;\n    }\n    \n    const startDateStr = formatDateToString(startDate);\n    const endDateStr = formatDateToString(today);\n    console.log(`📅 本次增量同步區間: ${startDateStr} 至 ${endDateStr}`);

    const commonHeaders = {\n      'accept': 'application/json',\n      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'\n    };

    // 3. 分批處理執行迴圈
    for (let i = 0; i < dbStockData.length; i++) {\n      const stock = dbStockData[i];\n      \n      if (i > 0 && i % 15 === 0) {\n        console.log(`⏳ 已同步處理 ${i} 檔，為保護 API 額度，強制休息 10 秒...`);\n        await sleep(10000);\n      }\n\n      console.log(`[同步與指標計算] (${i + 1}/${dbStockData.length}) ${stock.stock_id}`);\n\n      try {\n        // --- A. 抓取法人籌碼 ---
        const apiUrl = `https://api.finmindtrade.com/api/v4/data?dataset=TaiwanStockInstitutionalInvestorsBuySell&data_id=${stock.stock_id}&start_date=${startDateStr}&end_date=${endDateStr}&token=${FINMIND_TOKEN}`;\n        const res = await axios.get(apiUrl, { headers: commonHeaders });\n        \n        const dateMap = {};\n        if (res.data.status === 200 && Array.isArray(res.data.data)) {\n          res.data.data.forEach(row => {\n            const d = row.date;\n            if (!dateMap[d]) {\n              dateMap[d] = { \n                stock_id: stock.stock_id, date: d, price: null, change_value: 0, \n                f_buy:0, f_sell:0, fd_buy:0, fd_sell:0, it_buy:0, it_sell:0, ds_buy:0, ds_sell:0, dh_buy:0, dh_sell:0,\n                open: 0, max: 0, min: 0, trading_volume: 0,\n                ma10: null, ma20: null, ma60: null, rsi14: null // 預留您在資料庫新建立的指標欄位\n              };\n            }\n            if (row.name === 'Foreign_Investor') { dateMap[d].f_buy = row.buy; dateMap[d].f_sell = row.sell; }\n            else if (row.name === 'Foreign_Dealer_Self') { dateMap[d].fd_buy = row.buy; dateMap[d].fd_sell = row.sell; }\n            else if (row.name === 'Investment_Trust') { dateMap[d].it_buy = row.buy; dateMap[d].it_sell = row.sell; }\n            else if (row.name === 'Dealer_self') { dateMap[d].ds_buy = row.buy; dateMap[d].ds_sell = row.sell; }\n            else if (row.name === 'Dealer_Hedging') { dateMap[d].dh_buy = row.buy; dateMap[d].dh_sell = row.sell; }\n          });\n        }\n\n        // --- B. 抓取價格與開高低量 ---
        const priceApiUrl = `https://api.finmindtrade.com/api/v4/data?dataset=TaiwanStockPrice&data_id=${stock.stock_id}&start_date=${startDateStr}&end_date=${endDateStr}&token=${FINMIND_TOKEN}`;\n        const priceRes = await axios.get(priceApiUrl, { headers: commonHeaders });\n        \n        if (priceRes.data.status === 200 && Array.isArray(priceRes.data.data)) {\n          priceRes.data.data.forEach(pRow => {\n            const d = pRow.date;\n            if (!dateMap[d]) dateMap[d] = { stock_id: stock.stock_id, date: d, ma10: null, ma20: null, ma60: null, rsi14: null };\n            \n            dateMap[d].price = pRow.close;\n            dateMap[d].open = pRow.open;\n            dateMap[d].max = pRow.max;\n            dateMap[d].min = pRow.min;\n            dateMap[d].trading_volume = pRow.Trading_Volume;\n            dateMap[d].change_value = pRow.spread || 0;\n          });\n        }\n\n        // --- C. 💡 從 Supabase 讀取既有歷史舊資料來輔助計算技術指標 ---
        // 為了推算新的 MA60 均線，我們需要知道此前最新的 60 天價格歷史
        const { data: dbHistory, error: histErr } = await supabase\n          .from('stock_chips_daily')\n          .select('date, price')\n          .eq('stock_id', stock.stock_id)\n          .lt('date', startDateStr)\n          .order('date', { ascending: false })\n          .limit(65); // 撈取足夠的天數即可，若資料庫一開始是空的，回傳會是空陣列 []\n\n        if (histErr) console.error(`[警告] 讀取 ${stock.stock_id} 歷史資料失敗:`, histErr.message);\n\n        // 將舊資料轉為由舊到新的順序
        let historyPrices = dbHistory ? dbHistory.reverse() : [];\n        let newSortedDates = Object.keys(dateMap).sort(); // 本次要新增的日期序列\n\n        // 建立一個滾動價格序列池\n        let priceSequencePool = [...historyPrices.map(h => ({ date: h.date, price: h.price }))];\n\n        // 依時間正序逐日處理本次新抓到的資料，並一邊計算指標
        newSortedDates.forEach(dStr => {\n          const currentPrice = dateMap[dStr].price;\n          if (currentPrice !== null && currentPrice !== undefined) {\n            priceSequencePool.push({ date: dStr, price: currentPrice });\n          }\n\n          const poolLen = priceSequencePool.length;\n\n          // 1️⃣ 增量計算 MA10\n          if (poolLen >= 10) {\n            const sum10 = priceSequencePool.slice(-10).reduce((acc, c) => acc + c.price, 0);\n            dateMap[dStr].ma10 = parseFloat((sum10 / 10).toFixed(2));\n          } else {\n            dateMap[dStr].ma10 = null; // 資料庫歷史天數不足，留空白\n          }\n\n          // 2️⃣ 增量計算 MA20\n          if (poolLen >= 20) {\n            const sum20 = priceSequencePool.slice(-20).reduce((acc, c) => acc + c.price, 0);\n            dateMap[dStr].ma20 = parseFloat((sum20 / 20).toFixed(2));\n          } else {\n            dateMap[dStr].ma20 = null; // 留空白\n          }\n\n          // 3️⃣ 增量計算 MA60\n          if (poolLen >= 60) {\n            const sum60 = priceSequencePool.slice(-60).reduce((acc, c) => acc + c.price, 0);\n            dateMap[dStr].ma60 = parseFloat((sum60 / 60).toFixed(2));\n          } else {\n            dateMap[dStr].ma60 = null; // 留空白\n          }\n\n          // 4️⃣ 增量計算 RSI14 (標準威爾德平滑滾動法)\n          if (poolLen >= 15) {\n            let avgUp = 0;\n            let avgDown = 0;\n            let rsiInitialized = false;\n\n            // 使用整段歷史滾動計算確保平滑度不失真\n            for (let j = 1; j < priceSequencePool.length; j++) {\n              const diff = priceSequencePool[j].price - priceSequencePool[j - 1].price;\n              const currentUp = diff > 0 ? diff : 0;\n              const currentDown = diff < 0 ? Math.abs(diff) : 0;\n\n              if (!rsiInitialized) {\n                avgUp += currentUp;\n                avgDown += currentDown;\n                if (j === 14) {\n                  avgUp = avgUp / 14;\n                  avgDown = avgDown / 14;\n                  rsiInitialized = true;\n                }\n              } else {\n                avgUp = (avgUp * 13 + currentUp) / 14;\n                avgDown = (avgDown * 13 + currentDown) / 14;\n              }\n            }\n\n            if (rsiInitialized) {\n              if (avgDown === 0) {\n                dateMap[dStr].rsi14 = avgUp === 0 ? 50.00 : 100.00;\n              } else {\n                const rs = avgUp / avgDown;\n                dateMap[dStr].rsi14 = parseFloat((100 - (100 / (1 + rs))).toFixed(2));\n              }\n            } else {\n              dateMap[dStr].rsi14 = null;\n            }\n          } else {\n            dateMap[dStr].rsi14 = null; // 歷史天數不夠 15 筆，留空白\n          }\n        });\n\n        // --- D. 執行 Upsert 寫入資料庫 ---
        const rowsToUpsert = Object.values(dateMap);\n        if (rowsToUpsert.length > 0) {\n          const { error: upsertErr } = await supabase.from('stock_chips_daily').upsert(rowsToUpsert);\n          if (upsertErr) throw upsertErr;\n        }\n\n      } catch (err) {\n        console.error(`❌ 同步與指標計算 ${stock.stock_id} 錯誤: ${err.message}`);\n      }\n      await sleep(200); \n    }\n\n    console.log("🎉 智慧增量與技術指標計算同步流程全數完成！");\n  } catch (error) {\n    console.error("💥 全局同步流程發生嚴重致命錯誤:", error.message);\n    process.exit(1);\n  }\n}\n\nrun();
