name: Daily Auto LINE Notification to List

on:
 # schedule:
 #   # 💡 這裡就是台灣時間每天早上 07:10 自動執行 (等於 UTC 前一天晚上 23:10)
 #   - cron: '10 22 * * *'
  workflow_dispatch: # 保留手動觸發按鈕，方便你隨時測試

jobs:
  send-line-message:
    runs-on: ubuntu-latest
    env:
      USER_LIST: "U1d55204debbb0af1f992ec1d9a358f93 U3fd5afc17e5869f39772e6d55cec31e0 C7040d04f3e87e987cbaf7d2085fc3593"
    
    steps:
      - name: Loop through User List
        run: |
          for USER_ID in $USER_LIST; do
            echo "Sending to $USER_ID"
            curl -X POST https://api.line.me/v2/bot/message/push \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" \
              -d "{
                \"to\": \"$USER_ID\",
                \"messages\": [
                  {
                    \"type\": \"text\",
                    \"text\": \"📊 台股新聞\n\n今日最新的 AI 盤前情報分析報告已出爐，請點選下方連結查看完整資訊：\nhttps://chung05.github.io/Stock/docs/index.html\"
                  }
                ]
              }"
          done
